cask_args appdir: '/Applications'
tap "neovim/neovim"
tap "caskroom/versions"

brew "git"
brew "antigen"
brew "bat"
brew "gotop"
brew "fzf"
brew "jq"
brew "direnv"
brew "openssl"
brew "reattach-to-user-namespace"
brew "rg"
brew "tmux"
brew "zsh"
brew "z"
brew "nnn"
brew "neovim"
brew "heroku-toolbelt"
brew "hub"
brew "imagemagick"
brew "htop"
brew "fasd"
brew "python3"
brew "heroku"
brew "readline"
brew "redis"
brew "python3"
brew "httpie"
brew "pinentry-mac"
brew "postgresql"
brew "cockroach"
brew "memcached"
brew "overmind"
brew "telnet"
brew "wget"
bre "asdf"


brew "libyaml" # should come after openssl

brew "dfu-util"
brew "dfu-programmer"

cask "docker-edge"
cask "appcleaner"
cask "visual-studio-code"
cask "vnc-viewer"
cask "hocus-focus"
cask "tableplus"
cask "sidestep"
cask "skim"
cask "iina"
cask "tunnelbear"
cask "marked"
cask "beamer"
cask "cloudapp"
cask "amethyst"
cask "folx"
cask "dash"
cask "paw"
cask "vanilla"
cask "teensy"
cask "karabiner-elements"
cask "alfred"
cask "keybase"
cask "riot"

cask "chromium"
cask "firefox-developer-edition"
