cask_args appdir: '/Applications'
tap "osx-cross/arm"
tap "PX4/homebrew-px4" #arm-none-eabi toolchain
tap "osx-cross/avr"
tap "neovim/neovim"
tap "caskroom/versions"
tap "universal-ctags/universal-ctags"

brew "git"
brew "direnv"
brew "openssl"
brew "reattach-to-user-namespace"
brew "the_silver_searcher"
brew "tmux"
brew "zsh"
brew "z"
brew "unison"
brew "ranger"
brew "neovim/neovim/neovim"
brew "heroku-toolbelt"
brew "hub"
brew "imagemagick"
brew "htop"

brew "libyaml" # should come after openssl
brew "chruby"
brew "nodenv"
brew "ruby-install"
brew "node-build"

brew "arm-gcc-bin"
brew "avr-binutils"
brew "avr-gcc"
#brew "avr-gcc" this needs to have avr-gcc linked before installing
brew "avr-libc"
brew "dfu-util"
brew "dfu-programmer"

cask "docker-beta"
cask "appcleaner"
cask "visual-studio-code"
cask "flux"
cask "hocus-focus"
cask "iterm2-nightly"
cask "postico"
cask "sequel-pro"
cask "shiftit"
cask "sidestep"
cask "skim"
cask "vlc"
cask "tunnelbear"
cask "omnifocus"
cask "marked"
cask "beamer"
cask "cloud"
cask "dash"
cask "paw"
cask "screenhero"
cask "spotify"
cask "teensy"

cask "chromium"
cask "google-chrome-canary"
cask "opera"
cask "vivaldi"
cask "firefoxdeveloperedition"
