#!/bin/sh
# Dotfiles installer

SRCDIR="$HOME/src"
DOTFILES="$HOME/.dotfiles"
HOMESICK="$HOME/.homesick"
CONFIGDIR="$HOME/.config"
TMUXDIR="$HOME/.tmux"
PREZTODIR="$HOME/.zprezto"

# SRC Files for projects
if [[ ! -d "$SRCDIR" ]]; then
  mkdir "$SRCDIR"
fi

# Config Dir for NeoVim
if [[ ! -d "$CONFIGDIR" ]]; then
  curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

# Tmux plugin manager
if [[ ! -d "$TMUXDIR/plugins" ]]; then
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

# Change shell to zsh
if [[ ! -d "$PREZTODIR" ]]; then
  zsh && git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
  setopt EXTENDED_GLOB
  for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
    ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
  done
  chsh -s /bin/zsh
fi

# Build Dotfiles
cd "$DOTFILES"

sudo gem install homesick

homesick clone braidn/dotfiles
homesick symlink dotfiles

cd "$HOME"

# Keep Homesick dir but remove dotfiles dir
rm -rf "$DOTFILES"

# Hide Dock To Left
defaults write com.apple.dock pinning -string start \
&& write com.apple.dock static-only -bool TRUE \
&& write com.apple.dock autohide -bool TRUE \
&& defaults write com.apple.dock autohide-delay -float 100 \
&& defaults write com.apple.dock autohide-time-modifier -float 100 \
&& killall Dock

# Add Support for Needed Languages

asdf plugin-add crystal
asdf plugin-add elixir
asdf plugin-add erlang
asdf plugin-add nodejs
asdf plugin-add ruby

# Add Yarn support

curl -o- -L https://yarnpkg.com/install.sh | bash
