#!/bin/sh
# Dotfiles installer

ASDFDIR="$HOME/.asdf"

# Change shell to fish with fisher plugin manager
  curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
  echo “/usr/local/bin/fish” | sudo tee -a /etc/shells
  chsh -s /usr/local/bin/fish
fi

# Install ASDF
if [[ ! -d "$ASDFDIR" ]]; then
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf
  cd ~/.asdf
  git checkout "$(git describe --abbrev=0 --tags)"

  cd "$HOME"
fi

# Add Support for Needed Languages
if [[ "$ASDFDIR" ]]; then
  asdf plugin-add ruby
  asdf plugin-add nodejs

  bash -c '${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-release-team-keyring'
fi

# Add Yarn support
curl -o- -L https://yarnpkg.com/install.sh | bash

# Install NeoVim package manager
git clone https://github.com/k-takata/minpac.git ~/.config/nvim/pack/minpac/opt/minpac
